# Generated by Django 6.0.6 on 2026-06-11 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteversion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='current_note',
        ),
        migrations.AddField(
            model_name='noteversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='noteversion',
            constraint=models.UniqueConstraint(fields=('encounter', 'version_number'), name='unique_note_version_per_encounter'),
        ),
        migrations.AddConstraint(
            model_name='noteversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('encounter',), name='unique_draft_note_per_encounter'),
        ),
    ]
