# Generated by Django 6.0.6 on 2026-06-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_alter_noteversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteversion',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
