# Generated by Django 6.0.6 on 2026-06-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_noteversion_saved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='template',
        ),
    ]
